import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { SectionTitle } from '@/components/SectionTitle';
import { validationRepository } from '@/repositories/validationRepository';
export default function ValidationPage() {
    const { data, isLoading } = useQuery({
        queryKey: ['validation/last'],
        queryFn: () => validationRepository.last(),
    });
    return (_jsxs("div", { className: "max-w-5xl mx-auto px-6 py-12", children: [_jsx(SectionTitle, { eyebrow: "data quality", title: "Validation report", subtitle: "Rules classify issues into BLOCKING (run aborted, fallback to last forecast) and WARNING (logged, run continues)." }), isLoading && _jsx("div", { className: "text-muted", children: "Loading\u2026" }), data && (_jsxs(_Fragment, { children: [_jsxs("div", { className: "panel mb-6 flex gap-6", children: [_jsxs("div", { children: [_jsx("div", { className: "text-muted text-xs uppercase tracking-widest", children: "Blocking" }), _jsx("div", { className: "num text-3xl text-red-300", children: data.blocking_count })] }), _jsxs("div", { children: [_jsx("div", { className: "text-muted text-xs uppercase tracking-widest", children: "Warnings" }), _jsx("div", { className: "num text-3xl text-accent", children: data.warning_count })] })] }), _jsx("div", { className: "panel", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { className: "text-muted text-xs uppercase tracking-widest", children: _jsxs("tr", { children: [_jsx("th", { className: "text-left py-2", children: "Rule" }), _jsx("th", { children: "Severity" }), _jsx("th", { children: "Affected" }), _jsx("th", { className: "text-left", children: "Message" })] }) }), _jsx("tbody", { children: data.issues.map((i, k) => (_jsxs("tr", { className: "border-t border-white/5", children: [_jsx("td", { className: "py-2 font-mono", children: i.rule }), _jsx("td", { className: "text-center", children: _jsx("span", { className: i.severity === 'BLOCKING' ? 'badge-block' : 'badge-warn', children: i.severity }) }), _jsx("td", { className: "text-center num", children: i.affected_count }), _jsx("td", { className: "text-ink", children: i.message })] }, k))) })] }) })] }))] }));
}
